"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Braces, ChartColumn, Cloud, Database, GitBranch, Layers3, Palette, ShieldCheck, Target } from "lucide-react";
import { Career, Skill } from "@/lib/types";
import { useApi } from "@/lib/useApi";
import { SkillIcon, SkillIdentity } from "./SkillIcon";
import { CareerCard } from "./CareerCard";
import { LogoMarquee, TextEmerge } from "./HomeMotion";
import { SectionHeading, SkillProgress, Status } from "./ui";

const categoryCopy: Record<string, { text: string; icon: typeof Braces }> = {
  "Software Engineering": { text: "สร้างระบบ เว็บไซต์ และซอฟต์แวร์", icon: Braces },
  "AI & Machine Learning": { text: "พัฒนาโมเดลและระบบที่เรียนรู้จากข้อมูล", icon: Layers3 },
  Data: { text: "เปลี่ยนข้อมูลให้เป็นความเข้าใจและการตัดสินใจ", icon: Database },
  "Cloud & DevOps": { text: "ดูแลโครงสร้างพื้นฐานและการส่งมอบซอฟต์แวร์", icon: Cloud },
  Design: { text: "ออกแบบประสบการณ์ที่เข้าใจผู้ใช้งาน", icon: Palette },
  Marketing: { text: "เชื่อมต่อผู้คนด้วยกลยุทธ์และข้อมูล", icon: ChartColumn },
};

export function HomeContent() {
  const catalog = useApi<Career[]>("/careers");
  const skills = useApi<Skill[]>("/skills");
  const [selected, setSelected] = useState<number | null>(null);
  const technologies = (skills.data || []).filter(skill => skill.icon_kind === "simple-icons");
  const categories = Array.from(new Set((catalog.data || []).map(c => c.category)));
  const preview = (skills.data || []).filter(s => ["JavaScript", "React", "Next.js"].includes(s.name)).sort((a, b) => ["JavaScript", "React", "Next.js"].indexOf(a.name) - ["JavaScript", "React", "Next.js"].indexOf(b.name));
  const selectedSkill = preview.find(s => s.id === selected) || preview[0];
  return <>
    <LogoMarquee skills={technologies} />
    <section className="home-section product-statement"><p className="eyebrow">A clearer next step</p><TextEmerge><h2>ไม่ใช่แค่รู้ว่าขาดอะไร<br /><span className="muted">แต่รู้ว่าควรเริ่มจากตรงไหน</span></h2></TextEmerge><p className="lead">จากทักษะที่คุณมี สู่เส้นทางที่เรียงลำดับอย่างมีเหตุผล<br />เชื่อมเป้าหมายอาชีพกับก้าวเล็ก ๆ ที่ลงมือทำได้</p></section>
    <section className="home-section"><SectionHeading eyebrow="How SkillPath works" title="เปลี่ยนเป้าหมาย ให้เป็นแผนที่ชัดเจน" /><ol className="process-grid">{[["เลือก Career", "ค้นหาสายอาชีพที่คุณสนใจ"], ["ประเมิน Skill", "บอกระดับทักษะปัจจุบันของคุณ"], ["วิเคราะห์ Skill Gap", "เห็นระยะห่างจากเป้าหมาย"], ["สร้าง Roadmap", "เรียนตามลำดับพื้นฐานที่จำเป็น"], ["อัปเดต Progress", "ปรับแผนเมื่อทักษะของคุณเพิ่มขึ้น"]].map(([title, text], i) => <li key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
    <section className="home-section" id="career-categories"><div className="section-topline"><SectionHeading eyebrow="Find your direction" title="เส้นทางไหนที่เป็นคุณ"><p>เริ่มสำรวจจากสิ่งที่สนใจ แล้วค่อยสร้างเส้นทางของตัวเอง</p></SectionHeading><Link className="text-link" href="/careers">ดูทุกสายอาชีพ <ArrowUpRight size={18} /></Link></div><Status loading={catalog.loading} error={catalog.error} onRetry={catalog.retry} />{catalog.data && <div className="category-grid">{categories.map(category => { const matching = catalog.data!.filter(c => c.category === category); const info = categoryCopy[category]; const Icon = info?.icon || Braces; return <Link className="category-card card-link" href={`/careers?category=${encodeURIComponent(category)}`} key={category}><div className="category-top"><span className="category-icon"><Icon size={22} /></span><span className="muted">{matching.length} อาชีพ</span></div><h3>{category}</h3><p>{info?.text || "สำรวจทักษะและเส้นทางอาชีพ"}</p><small>{matching.slice(0, 2).map(c => c.title).join(" · ")}</small><ArrowUpRight className="category-arrow" size={18} /></Link>; })}</div>}</section>
    <section className="home-section split-section"><div><SectionHeading eyebrow="01 / Understand your gap" title="เห็นทักษะที่มี และสิ่งที่ต้องเติม"><p>เปรียบเทียบ Current Level กับ Target Level ให้เห็นภาพ รู้ว่าทักษะไหนพร้อมแล้ว และทักษะไหนควรพัฒนาต่อ</p></SectionHeading><Link href="/careers" className="text-link">เริ่มประเมินทักษะของคุณ <ArrowRight size={18} /></Link></div><div className="card preview-panel"><div className="panel-heading"><span><Target size={16} /> Skill Gap</span><span className="badge">ตัวอย่างการประเมิน</span></div>{[{ name: "JavaScript", current: 2, target: 5 }, { name: "React", current: 1, target: 4 }].map(item => <div className="preview-skill" key={item.name}><div className="row-between"><SkillIdentity name={item.name} skillType={item.name === "React" ? "Library" : "Programming Language"} /><span className="gap-value">Gap {item.target - item.current}</span></div><SkillProgress current={item.current} target={item.target} /></div>)}<p className="caption">ระดับสมมติสำหรับอธิบายการเปรียบเทียบ ไม่ใช่ผลของคุณ</p></div></section>
    <section className="home-section roadmap-preview-section"><SectionHeading eyebrow="02 / Connect the dots" title="พื้นฐานที่ดี ทำให้ก้าวต่อไปง่ายขึ้น"><p>Learning Roadmap เชื่อมทักษะที่ต้องเรียนก่อน ให้คุณเริ่มต้นอย่างมีทิศทาง</p></SectionHeading><Status loading={skills.loading} error={skills.error} onRetry={skills.retry} />{!!preview.length && <div className="preview-graph"><div className="preview-path">{preview.map((skill, i) => <div className="preview-path-item" key={skill.id}>{i > 0 && skill.prerequisites.some(p => p.skill_id === preview[i - 1].id) && <ArrowRight className="preview-connector" aria-hidden="true" />}<button className={`preview-node${selectedSkill?.id === skill.id ? " selected" : ""}`} aria-pressed={selectedSkill?.id === skill.id} onClick={() => setSelected(skill.id)}><SkillIcon name={skill.name} iconKey={skill.icon_key} iconKind={skill.icon_kind} size="lg" /><strong>{skill.name}</strong><span>{skill.skill_type}</span></button></div>)}</div>{selectedSkill && <div className="preview-node-detail" aria-live="polite"><GitBranch size={20} /><div><strong>{selectedSkill.name}</strong><p>{selectedSkill.prerequisites.length ? selectedSkill.prerequisites.map(p => `${p.skill_name} ≥ ${p.minimum_level}`).join(" · ") : "ไม่มี prerequisite ในข้อมูลทักษะนี้"}</p></div></div>}<p className="caption">ตัวอย่างบางส่วนจากข้อมูลทักษะจริง · เลือกทักษะเพื่อดูพื้นฐานที่จำเป็น</p></div>}</section>
    <section className="home-section split-section"><div className="readiness-explainer card"><div className="readiness-symbol" aria-hidden="true"><Target size={64} /><span>Career Readiness</span></div><h3>ทุกทักษะ มีความหมายต่อเป้าหมาย</h3><p>ความพร้อมพิจารณาระดับทักษะและน้ำหนักความสำคัญของ Requirement แต่ละข้อ</p><div className="readiness-formula"><span>ทักษะปัจจุบัน</span><ArrowRight size={16} /><span>Requirement</span><ArrowRight size={16} /><span>ความพร้อม</span></div></div><SectionHeading eyebrow="03 / Know where you stand" title="มองเห็นความก้าวหน้าของคุณ"><p>ดู Career Readiness จากผลประเมินจริง แล้วกลับมาอัปเดตเมื่อเรียนรู้เพิ่มขึ้น แผนจะปรับตามทักษะล่าสุดของคุณ</p><Link className="text-link" href="/dashboard">เปิด Dashboard <ArrowUpRight size={18} /></Link><p className="caption">คะแนนจะปรากฏหลังประเมินทักษะ ไม่ใช่การรับประกันการได้งาน</p></SectionHeading></section>
    <section className="home-section"><SectionHeading eyebrow="Explore the ecosystem" title="หนึ่งเป้าหมาย หลายทักษะที่เชื่อมกัน" /><div className="career-grid">{catalog.data?.slice(0, 3).map(career => <CareerCard key={career.id} career={career} />)}</div></section>
    <section className="home-section why-section"><SectionHeading eyebrow="Built around your progress" title="แผนที่เข้าใจได้ และปรับไปกับคุณ" /><div className="why-grid">{[{ icon: ShieldCheck, title: "ทุกลำดับมีเหตุผล", text: "ดูความสำคัญและ Skill Gap ที่ใช้จัดลำดับทักษะได้อย่างโปร่งใส" }, { icon: GitBranch, title: "ไม่ข้ามพื้นฐานสำคัญ", text: "ลำดับการเรียนเคารพ prerequisite ของแต่ละทักษะ" }, { icon: ArrowDown, title: "ก้าวหน้าแล้ว แผนก็ปรับ", text: "บันทึกระดับใหม่ แล้วคำนวณเส้นทางที่เหลือให้เหมาะกับคุณ" }].map(item => <article key={item.title}><item.icon size={24} /><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
  </>;
}
